practical-2

step-1

In [1]:
import pandas as pd

step-2

In [2]:
data = {
    "ID" : [101, 102, 103, 104, 104, 105, 106 ],
    "Name" : ["Rahul", "Amit", "Riya", "Ajay", "Naresh", "jenil"],
    "Age" : [20,20,20,22,23,28],
    "City" : ["Surat", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahmedabad"],
    "Marks" : [85,78,88,88,81,90,93]
 }

step-3

In [4]:
df = pd.DataFrame(data)

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat     85
1  102    Amit  20.0      Surat     78
2  103    Riya  20.0    Bharuch     88
3  104    Ajay  22.0    Bharuch     88
4  104  Naresh  23.0    Navsari     81
5  105   jenil  28.0      Surat     90
6  106    None   NaN  Ahmedabad     93

step-4

In [5]:
df.head()

    ID    Name   Age     City  Marks
0  101   Rahul  20.0    Surat     85
1  102    Amit  20.0    Surat     78
2  103    Riya  20.0  Bharuch     88
3  104    Ajay  22.0  Bharuch     88
4  104  Naresh  23.0  Navsari     81

step-5

In [6]:
df.head()

    ID    Name   Age     City  Marks
0  101   Rahul  20.0    Surat     85
1  102    Amit  20.0    Surat     78
2  103    Riya  20.0  Bharuch     88
3  104    Ajay  22.0  Bharuch     88
4  104  Naresh  23.0  Navsari     81

step-6

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    6 non-null      object
 2   Age     6 non-null      float64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 412.0+ bytes

step-7

In [8]:
df.describe()

               ID        Age      Marks
count    7.000000   6.000000   7.000000
mean   103.571429  22.166667  86.142857
std      1.718249   3.125167   5.209881
min    101.000000  20.000000  78.000000
25%    102.500000  20.000000  83.000000
50%    104.000000  21.000000  88.000000
75%    104.500000  22.750000  89.000000
max    106.000000  28.000000  93.000000

step-8

In [9]:
df.shape

(7, 5)

step-9

In [10]:
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

step-10

In [11]:
df.isnull()

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False   True   True  False  False

step-11

In [12]:
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    0
dtype: int64

step-12

In [13]:
df.isnull().sum().sum()

np.int64(2)

step-13

In [14]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat     85
1  102    Amit  20.0      Surat     78
2  103    Riya  20.0    Bharuch     88
3  104    Ajay  22.0    Bharuch     88
4  104  Naresh  23.0    Navsari     81
5  105   jenil  28.0      Surat     90
6  106    None   NaN  Ahmedabad     93

step-14

In [15]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    ID    Name        Age       City  Marks
0  101   Rahul  20.000000      Surat     85
1  102    Amit  20.000000      Surat     78
2  103    Riya  20.000000    Bharuch     88
3  104    Ajay  22.000000    Bharuch     88
4  104  Naresh  23.000000    Navsari     81
5  105   jenil  28.000000      Surat     90
6  106    None  22.166667  Ahmedabad     93

step-15

In [16]:
df["Name"] = df["Name"].fillna("Unknown")
df

    ID     Name        Age       City  Marks
0  101    Rahul  20.000000      Surat     85
1  102     Amit  20.000000      Surat     78
2  103     Riya  20.000000    Bharuch     88
3  104     Ajay  22.000000    Bharuch     88
4  104   Naresh  23.000000    Navsari     81
5  105    jenil  28.000000      Surat     90
6  106  Unknown  22.166667  Ahmedabad     93

step-16

In [17]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

step-17

In [18]:
df.duplicated().sum()

np.int64(0)

step-18

In [19]:
df = df.drop_duplicates()
df

    ID     Name        Age       City  Marks
0  101    Rahul  20.000000      Surat     85
1  102     Amit  20.000000      Surat     78
2  103     Riya  20.000000    Bharuch     88
3  104     Ajay  22.000000    Bharuch     88
4  104   Naresh  23.000000    Navsari     81
5  105    jenil  28.000000      Surat     90
6  106  Unknown  22.166667  Ahmedabad     93

step-19

In [20]:
df.rename(columns={"Marks":"Score"}, inplace=True)
df

    ID     Name        Age       City  Score
0  101    Rahul  20.000000      Surat     85
1  102     Amit  20.000000      Surat     78
2  103     Riya  20.000000    Bharuch     88
3  104     Ajay  22.000000    Bharuch     88
4  104   Naresh  23.000000    Navsari     81
5  105    jenil  28.000000      Surat     90
6  106  Unknown  22.166667  Ahmedabad     93

step-20

In [21]:
df["Age"] = df["Age"].astype(int)
df

    ID     Name  Age       City  Score
0  101    Rahul   20      Surat     85
1  102     Amit   20      Surat     78
2  103     Riya   20    Bharuch     88
3  104     Ajay   22    Bharuch     88
4  104   Naresh   23    Navsari     81
5  105    jenil   28      Surat     90
6  106  Unknown   22  Ahmedabad     93

step-21

In [22]:
df["Final Score"] = df["Score"] + 4
df

    ID     Name  Age       City  Score  Final Score
0  101    Rahul   20      Surat     85           89
1  102     Amit   20      Surat     78           82
2  103     Riya   20    Bharuch     88           92
3  104     Ajay   22    Bharuch     88           92
4  104   Naresh   23    Navsari     81           85
5  105    jenil   28      Surat     90           94
6  106  Unknown   22  Ahmedabad     93           97

step-22

In [23]:
df["Name"] = df["Name"].str.upper()
df

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      Surat     85           89
1  102     AMIT   20      Surat     78           82
2  103     RIYA   20    Bharuch     88           92
3  104     AJAY   22    Bharuch     88           92
4  104   NARESH   23    Navsari     81           85
5  105    JENIL   28      Surat     90           94
6  106  UNKNOWN   22  Ahmedabad     93           97

step-23

In [24]:
df["City"] = df["City"].str.lower()
df

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      surat     85           89
1  102     AMIT   20      surat     78           82
2  103     RIYA   20    bharuch     88           92
3  104     AJAY   22    bharuch     88           92
4  104   NARESH   23    navsari     81           85
5  105    JENIL   28      surat     90           94
6  106  UNKNOWN   22  ahmedabad     93           97

step-24

In [25]:
df["City"] = df["City"].str.strip()
df

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      surat     85           89
1  102     AMIT   20      surat     78           82
2  103     RIYA   20    bharuch     88           92
3  104     AJAY   22    bharuch     88           92
4  104   NARESH   23    navsari     81           85
5  105    JENIL   28      surat     90           94
6  106  UNKNOWN   22  ahmedabad     93           97

step-25

In [26]:
df.sort_values(by="Age", inplace=True)
df

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      surat     85           89
1  102     AMIT   20      surat     78           82
2  103     RIYA   20    bharuch     88           92
3  104     AJAY   22    bharuch     88           92
6  106  UNKNOWN   22  ahmedabad     93           97
4  104   NARESH   23    navsari     81           85
5  105    JENIL   28      surat     90           94

step-26

In [27]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!