Enrollment Number : 240840116045

## **practical-1**:- Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON ƒles using Pandas.

step-1

In [ ]:
import pandas as pd

step-2

In [ ]:
data = {
    "ID": [101,102,103,104,105,106,107],
    "Name": ["Rahul","Priya","Amit","Riya","Karan","Krisha","Harry"],
    "Age": [20,21,19,20,22,24,26],
    "City": ["Surat","Navsari","Valsad","Bharuch","Surat","Gandhinagar","Ahmedabad"],
    "Marks": [85,92,78,88,81,84,90]
}

step-3

In [ ]:
df = pd.DataFrame(data)
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   26    Ahmedabad     90

step-4

In [ ]:
df.to_csv("student.csv", index=False)
print("CSV file created successfully")

CSV file created successfully

step-5

In [ ]:
df.to_excel("student.xlsx", index=False)
print("Excel file created successfully")

Excel file created successfully

step-6

In [ ]:
df.to_json("student.json", orient = "records", indent = 4)
print("Json file created successfully")

Json file created successfully

step-7

In [ ]:
df_csv = pd.read_csv("student.csv")
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   26    Ahmedabad     90

step-8

In [ ]:
df_xlsx = pd.read_excel("student.xlsx")
df_xlsx

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   26    Ahmedabad     90

step-9

In [ ]:
df_json = pd.read_json("student.json")
df_json

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   26    Ahmedabad     90

step-10

In [ ]:
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

step-11

In [ ]:
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   26    Ahmedabad     90

step-12

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

step-13

In [ ]:
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  21.714286  85.428571
std      2.160247   2.497618   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  26.000000  92.000000

step-14

In [ ]:
df_csv.shape

(7, 5)

step-15

In [ ]:
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

step-16

In [ ]:
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

step-17

In [ ]:
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

step-18

In [ ]:
df_csv[["Age","Marks"]]

   Age  Marks
0   20     85
1   21     92
2   19     78
3   20     88
4   22     81
5   24     84
6   26     90

step-19

In [ ]:
df_csv[df_csv["Marks"] > 80]

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   26    Ahmedabad     90

step-20

In [ ]:
df_csv["Marks"].mean()

np.float64(85.42857142857143)

step-21

In [ ]:
df_csv.sort_values(by="Marks", ascending=False)

    ID    Name  Age         City  Marks
1  102   Priya   21      Navsari     92
6  107   Harry   26    Ahmedabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78

step-22

In [ ]:
print(df_csv)

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   26    Ahmedabad     90